### PR TITLE
Use MoneroThreadPoolExecutor for wallet creation

### PR DESCRIPTION
**Pull request by m2049r**
a further step in the quest to run all wallet operations in own threads with approporaite stack size

### CODE REVIEW

**Comment by BenedictP** [comment]
Do you really want to use AsyncTasks (they have some serious pitfalls and drawbacks) or is this only a temporary solution?

**Comment by m2049r** [comment]
Yes, I was thinking I do.

Rationale:
* Monero code needs a stack size of 5MB. This is not provided by the UI thread or default Threads.
* So threading needs to be customized: in my case MoneroHandlerThread and MoneroThreadPoolExecutor
* Wallet operations are done through WalletService during the lifetime of WalletActivity
* LoginActivity uses AsyncTask because it needs to combine background threads (for monero operations and not-so-long tasks like copying wallets and getting exchange rates) and then do stuff in the UI (through onPostExecute, avoiding more callbacks and runOnUIThread)

What are the pitfalls & drawbacks?

The ones I have read about are rotation (as the actvity is recreated), cancelling the thread (continues after Activity is destroyed) and limit on the number of AsyncTasks which can run in parallel.

In my case, the screen does not rotate. The jobs are really short (usually <5 seconds) so it doesn't matter if they finish normally. And I run one job at time.

At least that's the idea :)

**Comment by BenedictP** [comment]
> Monero code needs a stack size of 5MB. This is not provided by the UI thread or default Threads.

Other solutions like RxJava also support to customize the thread pool.

> In my case, the screen does not rotate.

So you plan to not support tablets? An App without screen rotation on a tablet is a big bummer for the user. To lock portrait mode is for the beginning a nice shortcut but not a long term solution.

I just want to raise this discussion because the project is current in an early stage. So it would be relative easy to change.

**Comment by m2049r** [comment]
You are right, I disabled the screen rotation so I could get on with the functionality. But it is not a long term solution. RxJava - I don't know it but I have read very positive articles. If you can change the current code to use RxJava, be better and not slower then go for it! Try to keep the coding style intact.

Maybe replace one or two AsyncTasks first so I can see what it's all about :)  Maybe even exactly this PR (wallet creation).

**Comment by m2049r** [comment]
Also, I really DISLIKE using third-party libraries - especially frameworks.  I think any orientation change issues can be solved using retained fragments or broadcasts and the other pitfalls need to be kept in mind.

EDIT: I am not saying we should not look at it and evaluate the need.

**Comment by BenedictP** [comment]
Ok. It's your project ;)

**Pull request merged**
