### PR TITLE
Update zh-rTW "strings.xml"

### PR DESCRIPTION
**Pull request by uiharu-s**
Chinese Trandtional update
- translated new strings
- correction and editing

### CODE REVIEW

**Review by erciccione — APPROVED** [review]
Looks good to me, thanks @uiharu-s :)

**Comment by 0140454** [comment]
Thanks @uiharu-s for update.

I noticed that you replaced some half-width exclamation marks with full-width ones.
Is it possible to replace all half-width punctuation with full-width ones for consistency?

And in my humble opinion, "Account" is translated to "帳戶", "Subaddress" is translated to "子地址" in Taiwan.

**Comment by m2049r** [comment]
@uiharu-s @0140454 are we good here, or do I wait for @0140454's suggestions to be honored?

**Comment by 0140454** [comment]
In my humble opinion, we should use accurate translated terms because zh-TW is for Taiwan.

Maybe i can update this translation including new strings introduced by ledger feature and make @uiharu-s be co-author?

**Comment by erciccione** [comment]
At this point i think it's better to merge this, then open another PR for ledger's stuff

**Comment by 0140454** [comment]
OK, I will open PR for Ledger after merging this.

**Review by m2049r — APPROVED** [review]

**Pull request merged**
