### PR TITLE
Update for Russian translation #370

### PR DESCRIPTION
**Pull request by v1docq47**
Update:

- strings.xml
- help.xml

Calling to review:
@monerorus @LvMsterfild @AJIekceu4 @TheFuzzStone

### CODE REVIEW

**Comment by m2049r** [comment]
why delete about.xml & the sk translations??

**Comment by v1docq47** [comment]
I apologize. In PR came the files that I did not change.
They didn't need to be removed?

**Comment by v1docq47** [comment]
Perhaps should close this PR and open a new one, where only the changes in strings.xml and help.xml?

**Comment by m2049r** [comment]
@v1docq47 yes, strings & help. thanks!

**Comment by m2049r** [comment]
it may help if you make a branch in your fork of the repository and dont work on master. then PR from the fork.

**Pull request closed without merging**
