### PR TITLE
strings.xml - Translation[German]

### PR DESCRIPTION
**Pull request by Leza89**
Added missing translations, corrected some grammar, tried to make it more newbie friendly and shorter
(i.e. No german speaker will know TX as "transaction" - "Empfangsadresse" instead of "Öffentliche Adresse" should make it more clear that this is where your money goes to)
This is in reference to PR #328 (closed)

### CODE REVIEW

**Comment by erciccione** [comment]
@Re-Diculous could you review this PR?

**Review by Re-Diculous — APPROVED** [review]
Good additions. Easier to comprehend. S/he also caught an actual mistake on line 240. Thumbs up

**Review by erciccione — APPROVED** [review]

**Comment by Leza89** [comment]
@Re-Diculous Thank you.

**Comment by crtlib** [comment]
@Leza89 I think "Wallet" should appear untranslated only in names and titles. As a regular word, it should be translated as "Börse" / "Geldbörse" / "Geldtasche", shouldn't it? Denglisch bringt Deutsch um 😟

**Comment by Leza89** [comment]
@crtlib Well.. In that case I would go for "Geldbörse" probably. The question remains what you do with
(114) - "Walletspeicherung fehlgeschlagen!"
(309) - "View Only Wallet wiederherstellen"

Things like 
(308) - "Neue Geldbörse erstellen" sound about right but if you translate the above.. Well I can't think of a good way to translate those.
"Geldbörsenspeicherung fehlgeschlagen" or "Geldbörse konnte nicht gespeichert werden" sound stupid to me. Not to mention "Berechtigungslose Geldbörse...", "Geldbörse nur zum Anzeigen...", "Anschaugeldbörse..".

If you translate Wallet in one place, you have to translate it everywhere. Also translating "View Only" risks that you completely change the name and if somebody looks for support, he will not be able to find it outside of a german community (easily).

**Comment by Re-Diculous** [comment]
TBH, I like to pull the example of the french computer ("l'ordinateur"). Yes it's their word, yes it's good french, yes it's just making it awkward because the whole world (minus france) uses the word "computer". I'd keep the "wallet". Translation is best if it keeps a balance between accessibility of the topic, and a connection to the general public who talks about that topic. Imagine you don't know the word "wallet" and try to read up on some error you have... You'd be completely disconnected from the space.

**Comment by Leza89** [comment]
@Re-Diculous My line of thought as well. Just way better phrased. I guess it's better to treat "Wallet" as a name.

**Review by m2049r — APPROVED** [review]

**Pull request merged**
