### PR TITLE
Update French & Turkish translations

### PR DESCRIPTION
**Pull request by cardpuncher**
Mainly for the Sidekick part, also added a few missing strings to the French translation and reverted to use the original "Ledger" word in the Turkish one.

### CODE REVIEW

**Comment by ordtrogen** [comment]
Wouldn't it be preferable to have separate PRs for the Turkish and French updates? Easier to review.

(I think the French update looks legit, though. Just did a quick review)

**Comment by cardpuncher** [comment]
On 20.10.2024 11:59, Ordtrogen wrote:
> Wouldn't it be preferable to have separate PRs for the Turkish and 
> French updates? Easier to review.

Should I close this PR and open two new ones, one for French and another 
one for Turkish?

**Comment by lucasmz-dev** [comment]
Would you like me to import this into Weblate? #966

**Comment by cardpuncher** [comment]
On 6.11.2024 02:03, Lucas wrote:
> Would you like me to import this into Weblate? #966 <https://github.com/ 
> m2049r/xmrwallet/pull/966>

Of course. Thanks for your work on this.

**Comment by lucasmz-dev** [comment]
OK, you can leave this open until (if) that gets merged

**Comment by m2049r** [comment]
please check & resolve the conflicts

**Comment by lucasmz-dev** [comment]
@cardpuncher I can do this for you if you'd like

**Comment by cardpuncher** [comment]
On 7.12.2024 17:44, Lucas wrote:
> @cardpuncher <https://github.com/cardpuncher> I can do this for you if 
> you'd like

Hey, yeah that would be great. If my latest change doesn't fix the 
issues, I'm letting you finish the job. Thanks!

**Comment by cardpuncher** [comment]
@lucasmz-dev has a new PR https://github.com/m2049r/xmrwallet/pull/984 including these translations, so I think closing this one makes sense.

**Pull request closed without merging**
