### PR TITLE
update pt-BR translation

### PR DESCRIPTION
**Pull request by bitlamas**

### CODE REVIEW

**Comment by erciccione** [comment]
Thank you vp11 :)
@netrik182 could you review?

**Comment by netrik182** [comment]
Yes, I do.

**Comment by netrik182** [comment]
Hi @vp11. I noticed that lines from 157 to 164 are missing the translation. Could you add them so I can review everything all together? Thank you.

**Comment by bitlamas** [comment]
> Hi @vp11. I noticed that lines from 157 to 164 are missing the translation. Could you add them so I can review everything all together? Thank you.

Good catch, I don't know how I missed that block. I gave a quick look on the other files and they appear alright.

**Review by m2049r — APPROVED** [review]

**Review by erciccione — APPROVED** [review]

**Comment by erciccione** [comment]
Thank you @vp1111 @netrik182 :)

**Pull request merged**
