### PR TITLE
Swedish translation #236

### PR DESCRIPTION
**Pull request by noooxxi**
I and [ordtrogen](https://github.com/ordtrogen) have completed the Swedish translation of Monerujo
https://taiga.getmonero.org/project/erciccione-monero-localization/task/236

### CODE REVIEW

**Comment by m2049r** [comment]
Thanks!

Missing translations:
    
- info_crazypass_enabled
- prompt_fingerprint_auth
- bad_fingerprint
- generate_fingerprint_hint
- generate_fingerprint_warn

Please remove:

- about_licenses
- connect_stagenet
- connect_testnet
- connect_mainnet

**Comment by noooxxi** [comment]
I have removed the strings. I was however unable to find where the missing translations are located, please tell me where they are supposed to be.

**Comment by erciccione** [comment]
~~@noooxxi you can find the missing strings in the source file: https://github.com/m2049r/xmrwallet/blob/master/app/src/main/res/values/strings.xml~~

@ordtrogen @noooxxi both this PR and #261 translate `strings.xml` can you drop the changes on that file in this PR so we can use the updated one in #261 ?

**Comment by ordtrogen** [comment]
@noooxxi and I had agreed via mail that I'd create the PR for strings.xml (#261) so I'm not sure why it was included in this one also.

**Comment by erciccione** [comment]
@noooxxi @ordtrogen Can you fix this and/or #261 so that we can add Swedish

**Pull request merged**
