### PR TITLE
Japanese translation added

### PR DESCRIPTION
**Pull request by joshuamarques**
Japanese translation added.

### CODE REVIEW

**Review by m2049r — APPROVED** [review]

**Comment by m2049r** [comment]
@joshuamarques thank you so much!!

@erciccione do we have someone to review this, or can i take merge it asis?

**Comment by m2049r** [comment]
@joshuamarques can you please rebase to master or just add

    <string name="backup_success">Backup successful</string>

to the end of strings.xml

**Comment by erciccione** [comment]
maybe @sanecito could review?

**Comment by scottAnselmo** [comment]
@erciccione Will look at it this afternoon after I get back from taiko!

Edit: Had time to read through policy and help. Didn't notice any typos. Will audit the individual strings tomorrow for typos and alignment w/ the Monero GUI terminology.

**Comment by scottAnselmo** [comment]
@erciccione @m2049r : Solid localization. Don't see any issues with merging. Great contribution Joshua!

**Pull request merged**
