### PR TITLE
Add Arabic Translation !

### PR DESCRIPTION
**Pull request by Justxd22**
Translated and Added:

 - values-ar/
 - about.xml
 - help.xml
 - strings.xml

By following the translation guide, Tested and ready for merge!

### CODE REVIEW

**Comment by Justxd22** [comment]
Screenshot_20240120-012212_monerujo
Screenshot_20240120-012218_monerujo

**Comment by jermanuts** [comment]
Bruh this is a meme translation.

>بص وراك

>انا امن اشطاا

This is Egyptian not Arabic.

**Comment by Justxd22** [comment]
@jermanuts thanks for reviewing my work, I'm a native speaker with Egyptian accent Lines mentioned were intentionally wrote in Egyptian accent, As i thought it would be more clear explaining/Getting user attention in important warnings, I tested it with real people around and it was fine

I'm happy to edit these if you think it would interrupt with the user understanding of important stages of the wallet

**Comment by jermanuts** [comment]
> I'm happy to edit these if you think it would interrupt with the user understanding of important stages of the wallet

Sure.

**Comment by Justxd22** [comment]
@jermanuts would be awesome if you reviewed again, i fixed some lines Thanks.

**Comment by jermanuts** [comment]
@Justxd22  Add spacing, you removed spaces between lines, see the original https://github.com/m2049r/xmrwallet/blob/master/app/src/main/res/values/strings.xml

>معرف

معرّف do all

>أنفاق مونيرو الحلو الخاصة بي

مونيروجو Like in the original string

>لصق 

ألصق

>العقد، في الطريق

العقد، على طريقتك

Translate Tor to تور , Monero to مونيرو and Monerujo to مونيروجو **be consistent**

Also you didn't change the about.xml file, monerujo is transliterated to مونيروجو only once then monerujo is used instead of the transliteration.

@m2049r Can we transliterate monerujo? because it breaks RTL when used at the beginning of any sentences like
image

**Comment by Justxd22** [comment]
@jermanuts Big thanks for reviewing !

**Review by jermanuts — APPROVED** [review]

**Comment by jermanuts** [comment]
https://github.com/m2049r/xmrwallet/issues/426 @m2049r any updates?

**Comment by jermanuts** [comment]
@Justxd22 


ال/حافظة -> ال/محفظة

رمز الاستجابة السريعة -> رمز QR

**Comment by Justxd22** [comment]
@jermanuts thanks!

note other "حافظة are referring to clipboard

**Comment by jermanuts** [comment]
>note other "حافظة are referring to clipboard

ah, ok 😄

**Comment by m2049r** [comment]
> Can we transliterate monerujo? because it breaks RTL when used at the beginning of any sentences like

@anhdres please review this - esp. the comment above

**Comment by anhdres** [comment]
I'd transliterate *Monerujo*, specially if it improves the way a user may refer to it verbally, because transliterating it should preserve that.

If it were only for the left vs right layout I'd just add a word in Arabic before Monerujo (that makes sense, of course) and solve it that way.

@m2049r The only use case where literal *Monerujo* needs to be preserved (I'm guessing) is in the legal text, because I assume it should match perfectly with the name of the app.

According to Google, seems like a fair transliteration:
image

**Comment by jermanuts** [comment]
Yep, like Monero, the transliteration for it in Arabic is more popular, also with Tor. مونيرو and تور.

**Comment by jermanuts** [comment]
@Justxd22 lets translate all instances of Monerujo to مونيروجو except the legal stuff, append the original name and the Arabic transliteration afterwards to preserve RTL. Like: 

مونيروجو (Monerujo)  ................................................

**Comment by anhdres** [comment]
> @Justxd22 lets translate all instances of Monerujo to مونيروجو except the legal stuff, append the original name and the Arabic transliteration afterwards to preserve RTL. Like:
> 
> مونيروجو Monerujo ................................................

Perfect, do it the way you need (left or right) so that it doesn't break the layout again. You can put (Monerujo) between brackets for example.

**Comment by Justxd22** [comment]
- All monerujo -> مونيروجو
- All Legal stuff in about.xml monerujo -> `مونيروجو (Monerujo)`

**Comment by Justxd22** [comment]
Ready for merge

Note: there was changes in EN locale to fix some typos. https://github.com/m2049r/xmrwallet/pull/925/commits/90a0654a9c2a7163c4771afd2cbfa8a488d8e766

**Comment by lucasmz-dev** [comment]
That's a correction? Is Monerujo an extended name for Moneroj? My understand was that Moneroj was the plural for Monero, as like, the coin.

**Comment by Justxd22** [comment]
@lucasmz-dev no idea it's my first time i see "moneroj" i thought it's a typo? Should i drop it?

**Comment by lucasmz-dev** [comment]
I'm not sure, to be honest. I'd search more on it...

When I posted the last comment I thought you were the owner of the repo for some reason (?)

On English Wikipedia, I see it being described as that, if you can find any docs from like, getmonero.org saying similar or at least using that word in that context, I'd keep it that way.

**Comment by Justxd22** [comment]
Haha nah I'm just a contributor, maybe @m2049r can confirm this?

**Comment by Justxd22** [comment]
@anhdres can you please review this 🙏

**Comment by anhdres** [comment]
*moneroj* is the plural for *monero*, but I think you can change it to *moneros* or the equivalent in your language if you think it helps with understanding.

*monerujo* supposedly means wallet in Esperanto.

**Comment by Justxd22** [comment]
@anhdres can you check this https://github.com/Justxd22/xmrwallet/commit/90a0654a9c2a7163c4771afd2cbfa8a488d8e766

**Comment by anhdres** [comment]
I should read moneroj and not Moneroj, but definitely not Monerujo. It's talking about the coins, not the app.

**Comment by Justxd22** [comment]
@anhdres done, Ready for merge!

**Comment by lucasmz-dev** [comment]
Would you like me to import this into Weblate? #966

**Comment by Justxd22** [comment]
@lucasmz-dev yes please, but i need this merged first so it counts as contribution

**Comment by lucasmz-dev** [comment]
DW, you get credits in Git with Weblate
Though it won't be signed (cryptographically) by you (but instead by Weblate) if you've been doing that

**Comment by Justxd22** [comment]
@lucasmz-dev shouldn't this pr be merged to the codebase ? so you can pull the translations on weblate

**Comment by lucasmz-dev** [comment]
No, I can do this without that, though it won't include the changes to the English file (I don't think this is a great PR to do that either)

Why exactly do you want it to "count as a contribution"? Do you want GitHub to notice it and allow you to pin it or something on your profile?

**Comment by Justxd22** [comment]
[edit] the plural was changed then later anhdres said it was intentional so i dropped it but it looks like i did it in lower case

@lucasmz-dev the English file only edits "moneroj" plural, i can drop English if that's what is stopping this PR, 

Yes i want to be added to the contribution list of this repo and pin it as well to my profile 🙂 (I'm building my GitHub as an SE student)

**Comment by lucasmz-dev** [comment]
ok, i'll leave this for you to manage then

**Comment by jermanuts** [comment]
@lucasmz-dev can we just merge already? This translation was bounty https://bounties.monero.social/posts/100/1-100m-arabic-language-in-monerujo-wallet. I'm sorry but I don't see why we should postpone it longer than it have been already (almost a year). @Justxd22 Why a translation contribution would be any relevant to your Github profile as "SE student"?

**Comment by Justxd22** [comment]
@lucasmz-dev dropped English, @m2049r ready for merge

**Review by m2049r — APPROVED** [review]

**Comment by Justxd22** [comment]
Pleasure working with you all thanks

**Pull request merged**
