### PR TITLE
PT-PT translations updated

### PR DESCRIPTION
**Pull request by kic0**
translations added and updated for PT-PT

### CODE REVIEW

**Comment by erciccione** [comment]
@vp1111 @netrik182 @botoserelepe  Could you guys give this a review?

**Review by m2049r — APPROVED** [review]

**Comment by m2049r** [comment]
@kic0 please also 'fix' `menu_info` as it was chnaged to "Show Secrets!" - thanks!!

**Comment by m2049r** [comment]
@kic0 don't worry about the conflicts - i will fix those - can you please re-translate `<string name="menu_info">Mostrar Detalhes</string>` to "Show Secrets!"?

**Comment by erciccione** [comment]
@m2049r Fixed conflicts, added translation of `Show Secrets`, fixed a typo. Chatting live with @kic0 in #monero-translations

**Pull request merged**
