### PR TITLE
CrAzYpass implementation

### PR DESCRIPTION
**Pull request by m2049r**
Based on this post & paper:
- https://www.reddit.com/r/Monero/comments/85n9u3/crazy_secure_protection_for_android_monero_wallets/
- https://monerujo.io/recources/crazy_secure_passphrase.pdf

In addition. we have decided to make the CrAzYpass a string of uppercase alphanumerics ```[2-9A-HJ-NP-Z]``` (i.e. no 0,1,O,I) with spaces after every four characters. Thus the 256-bit key is encoded base 32. There are always 13 groups of 4 characters (padded with ```2```'s if necessary).

### CODE REVIEW

**Comment by m2049r** [comment]
@erciccione @hrumag @Lafudoci @anhdres

I have added the new/changed english texts to the the 'es', 'it' and 'zh-TW' translations.
Only two files are affected.

- ```strings.xml```: the english text is enclosed in ```[``` and ```]``` so you can easily find the strings in need of translating by searching for ```]</string>```

- ```help.xml```: one section ("Wallet Files Recovery Password") is added in the ```help_details``` section.

Please note, that in help.xml, texts need ```'``` to be written as ```&apos;``` and ```"``` as ```\"```.

Maybe you want to add something to the ```credits_text``` in ```about.xml```.

Thank you all very much!

**Comment by erciccione** [comment]
Got it, I updated the instructions on Taiga: https://taiga.getmonero.org/project/erciccione-monero-localization/wiki/monerujo

**Comment by Lafudoci** [comment]
@m2049r  I'm working on it. I'll make PR when it's done. And I am wondering should I put all the contributors during translation (including reviewers) in credits_text? Or just commit contributors?

**Comment by m2049r** [comment]
the credits overlay is very small and should stay that way - but it should probably link to a full list of contributors. either in the app or maybe github or the website.

**Comment by Lafudoci** [comment]
So should I put me and another commit contributor who translated policy in credits_text ? Or better leave it for code developers and wait for the full list page/link?

**Pull request merged**
