### PR TITLE
Russian Translation #244

### PR DESCRIPTION
**Pull request by ghost**
#244 Russian translate / done, need test

### CODE REVIEW

**Comment by ghost** [comment]
calling to review:
@TheFuzzStone @LvMsterfild @AJIekceu4

**Comment by m2049r** [comment]
how is this related to #278 ?

**Comment by erciccione** [comment]
@ghost @m2049r please close this issue, see [comment](https://github.com/m2049r/xmrwallet/pull/278#issuecomment-387271827)

**Comment by erciccione** [comment]
ping @m2049r

**Pull request closed without merging**
