### PR TITLE
Ukranian translation for Monerujo

### PR DESCRIPTION
**Pull request by TheFuzzStone**
Ping to review: @LvMsterfild @v1docq47

### CODE REVIEW

**Review by LvMsterfild — APPROVED** [review]

**Comment by TheFuzzStone** [comment]
@v1docq47, fixed a few typos in Russian translation. Can you check it? Thanks!

**Review by m2049r — CHANGES_REQUESTED** [review]
Please make sure to escape apostrophes (as `\'` or `&apos;`) like in  "ім'я гаманця".

Click on the "Detail" link under "All checks have failed" to see possible other errors in the black window.

**Comment by TheFuzzStone** [comment]
@m2049r, now we have "_All checks have passed_", so all is ok?
Sorry, I'm a noob with GIT :-/

**Comment by erciccione** [comment]
Yes, @TheFuzzStone, now it's fine. Happy to see this finally completed. Thank you.
Next time, please open another PR for changes to another language.

Task on Taiga: https://taiga.getmonero.org/project/erciccione-monero-localization/task/251

**Review by erciccione — APPROVED** [review]
Yes, @TheFuzzStone, now it's fine. Happy to see this finally completed. Thank you.
Next time, please open another PR for changes to another language.

Task on Taiga: https://taiga.getmonero.org/project/erciccione-monero-localization/task/251

**Comment by v1docq47** [comment]
Забыл написать, новый материал отправлю уже завтра.
Спасибо :)

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by m2049r** [comment]
@TheFuzzStone perfect :+1:

**Review by m2049r — APPROVED** [review]

**Pull request merged**
