### PR TITLE
First time to learn github for Monero translation of chinese.

### PR DESCRIPTION
**Pull request by bitOMG**
非常荣幸！It's my honor.
First time to learn github for Monero translation of chinese.

### CODE REVIEW

**Comment by erciccione** [comment]
In contact with him on reddit
@m2049r the folder should be renamed `zh_rCN` right?

**Comment by m2049r** [comment]
yes ```zh_rCN```

**Comment by m2049r** [comment]
yes ```values-zh-rCN```

**Comment by erciccione** [comment]
@m2049r Some strings are missing, do you have an automated way to look for them, or should we check manually? This is good to know for future translations as well

**Comment by m2049r** [comment]
@erciccione I have a (mostly) automated way:

Missing translations:
    
- info_crazypass_enabled
- prompt_fingerprint_auth
- bad_fingerprint
- generate_fingerprint_hint
- generate_fingerprint_warn

Please remove:

- connect_stagenet
- connect_testnet
- connect_mainnet

**Review by erciccione — APPROVED** [review]

**Comment by erciccione** [comment]
@m2049r check please, but i think this one can be merged

**Review by m2049r — APPROVED** [review]

**Pull request merged**
