### PR TITLE
Adjusted visibility of fields and methods.

### PR DESCRIPTION
**Pull request by EarlOfEgo**
Adjusted the visibility of mostly fields, some methods and not really a class since those look fine to me.

### CODE REVIEW

**Comment by m2049r** [comment]
thank you very much! BUT STOP WHAT YOU ARE DOING! becaue I have rewritten huge parts of the UI and not committed yet.

sorry for that!!  i am nearly done, and then will incorporate your changes into the new code.

**Comment by m2049r** [comment]
ok, pushed the UI changes. sorry again for the inconvenience.

**Comment by EarlOfEgo** [comment]
@m2049r I resolved the conflicts.

**Comment by m2049r** [comment]
thank you!

**Pull request merged**
